### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by jakemauer** [IainPHay/ESPHome-bed-occupancy-FSR#1]
Hey Iain, thanks for writing this up and sharing your files. I came across your repo from this video: https://www.youtube.com/watch?v=gZ1tmHesJXA

I have a few questions,
1. Would you be able to share your bill of materials? I'm interested in which variable resistors and/or other parts you used.
2. Can you elaborate on the difference between the two Gerber zips? In the readme you said one was for adding a BME280 but it looks like both boards have a spot for it. 
3. Would you do anything different if you were starting from scratch?

Thank you!

**Comment by IainPHay** [comment]
Hey Jake,

Thanks for the questions been meaning to update this for a while including a proper BOM. This project has been in place for months now and I've not needed to do any adjustment on it at all very pleased with it.

1  3296W-103 3296 W 10K ohm Trim Pot Trimmer Potentiometer  x2

2  PCB TERMINAL BLOCKS  3 WAY 15A 300V 5mm PITCH INTERLOCKING  x 2

3 Extra-long force-sensitive resistor (FSR) (Interlink 408) ([https://www.adafruit.com/product/1071) ](url) x 2

4 Female Header Edge Pins Strip 0.1" 2.54mm For Breadboard PCB For Dupont (30 pin or cut down larger) x2 

5 Female Header Edge Pins Strip 0.1" 2.54mm For Breadboard PCB For Dupont (4 pin) x1

6 36pin ESP32 [https://www.banggood.com/ESP32-Development-Board-WiFi+bluetooth-Ultra-Low-Power-Consumption-Dual-Cores-ESP-32-ESP-32S-Board-Geekcreit-for-Arduino-products-that-work-with-official-Arduino-boards-p-1109512.html?cur_warehouse=CN&rmmds=buy](url)

Good catch on the Gerber yes both of those have the VIN GND SCL and SDA included and labelled for BME280 but to be honest you can connect any i2c to that, don't mount directly through as temp will be off, The one to use is the ground plane one as that's a better design. I'll remove the other. You don't need to connect anything if you don't want.

I wouldn't do anything different to be honest as it's working great, I also use it as a bluetooth proxy as well and use it for room presence for iwatch. I do need to design a nice 3D printed case for it, at the moment it's just in an old junction box but that works well enough. a 36pin ESP32 was perhaps not the wisest choice as they seem to be harder to come by, at some point this week I'll rework it for other pin formats as 30 and 38 are more common. That's probably the only issue to replicate it but I've listed one from banggood above, not the exact one I used but should work.

Your trim pot values may need to be different depending on the weight of the mattress, you can do the calculation to get a rough idea but to be honest I don't think that's needed. With a 10K trim pot just set it up and keep turning down until the voltage drops to about 2.7V and you are in a good spot, higher is technically better but I've found that allows for a little variability for weights of different bedding etc.

**Comment by jakemauer** [comment]
Thanks for the detailed response! I got all my parts and got your .yaml setup working on my ESP32. Today was my first foray into ESPHome so thank you for sharing all your work. Based on some quick tests with my multimeter and seeing the ESP32's values right there in Home Assistant, I'm hopeful I'll be able to knock this out before the end of the weekend.

**Comment by dvbit** [comment]
ThNKS
